### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by leo67867** [BUTSpeechFIT/DiaPer#8]
Hello, I am processing and training the AISHELL-4 dataset using the command:

python diaper/train.py -c DiaPer/models/10attractors/SC_LibriSpeech_2spk_adapted1-10_finetuneAISHELL4mix/train.yaml,

where I modified init_epochs: 0 and init_model_path: ''. I split the AISHELL-4 dataset into a training and validation set with an 8:2 ratio. After training, I tested my model on the test set, but the results were different from yours. For example, for L_R003S01C02, I got a DER of 72.57, whereas yours was 47.37. For M_R003S01C01, my result was 65.53, but yours was 34.28. Also, I got my best results around the 10th epoch, whereas you got yours around the 190th-200th epoch.

Could you please share the specific details of your data splitting or processing methods? Do you have any suggestions on what might be going wrong with my approach and how I can improve it? Thank you.

**Comment by fnlandini** [comment]
Hi @leo67867 
I guess you are choosing the epoch based on the loss on development set, correct? I am attaching the 
[tensorboard.zip](https://github.com/user-attachments/files/17125822/tensorboard.zip) logs. You can see that in my case also the dev loss reached the lowest in just a few epochs. However, if you look at the dev_DER, you will see that it can still improve further. I observed this in a few of the fine-tuning steps with different sets. The attractor existence loss eventually grows but the BCE activation one improves on the dev set.
Have you tried evaluating your model for epoch 200? I expect you will get results more similar to mine. You can also try using the whole train set (instead of 80% of it) and run for 200 epochs as I did. In this case, since I used the test set as validation, I did not choose the number of epochs very carefully and just picked 200 as a reasonable guess.
My other question is if you are mixing the channels of AISHELL-4 to obtain the waveforms. That is what I did and I did not try using a single channel, for example. I am not sure if using a single channel might cause large degradation.

I hope this helps.
Federico

**Comment by leo67867** [comment]
Hello,thank you for your response. I followed your advice and used the entire training set, running it for 200 epochs and using the test set for validation. The results were slightly better than when I used 80% of the training set, but the performance is still significantly lower compared to your results. As you suggested, I converted the AISHELL-4 audio to mono-channel as input data because I encountered an error when trying to use the original 8-channel AISHELL-4 audio. This error prevented the code from running properly. The error details are as follows:
python DiaPer/diaper/train.py -c DiaPer/models/10attractors/SC_LibriSpeech_2spk_adapted1-10_finetuneAISHELL4mix/train.yaml
pre_crossattention 66048
latent_attractors 16384
encoder_attractors 1788672
latents2attractors 1280
counter 129
frame_encoder 2465920
Total trainable parameters: 4338433
miniconda3/envs/DiaPer/lib/python3.7/site-packages/librosa/util/decorators.py:88: UserWarning: n_fft=512 is too small for input signal of length=8
  return f(*args, **kwargs)
Warning: ('20200616_M_R001S01C01', 0, 1500) is empty: (0, 257, 240000)
Traceback (most recent call last):
  File "DiaPer/diaper/train.py", line 521, in <module>
    train_loader, dev_loader = get_training_dataloaders(args)
  File "DiaPer/diaper/train.py", line 284, in get_training_dataloaders
    Y_train, _, _, _, _, _ = train_set.__getitem__(0)
  File "DiaPer/diaper/common_utils/diarization_dataset.py", line 131, in __getitem__
    raise ValueError(f"Encountered an empty sequence at index {i}, and no saved sequence is available.")
ValueError: Encountered an empty sequence at index 0, and no saved sequence is available.

Are you able to handle multi-channel audio data? I’m not sure where the issue might be, or how I should proceed. I would greatly appreciate any guidance or suggestions you could provide.Thank you very much for your assistance!

**Comment by fnlandini** [comment]
Hi @leo67867 
Unfortunately, the code does not support multi-channel input. If you mixed the channels to obtain a mono file, then that is the same as I did.
My suggestion is that you compare the tensorboard I shared and the one of your training. Perhaps that will give a hint of what could be different. Otherwise, I am sorry but I am not sure what could be different. In case it is useful, I am attaching the data folders for train and test in case it is useful for you to spot any difference.  
[AISHELL4_data.tar.gz](https://github.com/user-attachments/files/17308924/AISHELL4_data.tar.gz)

**Comment by fnlandini** [comment]
Closing due to inactivity

**Comment by leo67867** [comment]
Hello@fnlandini
  I have used the AISHELL4_data.tar.gz dataset as provided and applied the configuration file /DiaPer/models/10attractors/SC_LibriSpeech_2spk_adapted1-10_finetuneAISHELL4mix/train.yaml. I modified the data input and output paths for training from scratch. However, I noticed that my dev DER after training is higher than yours, and I would like to understand why your initial dev DER is reported as 20.29，and then it will continue to decline to around 13.But mine will drop from 100 to around 23.
I have uploaded both the train.yaml configuration file and the generated TensorBoard logs for your reference. I would greatly appreciate your insights and any suggestions on how I can improve my results.
Looking forward to your reply.Thank you in advance for your help!
[mine.zip](https://github.com/user-attachments/files/18005257/mine.zip)

**Comment by fnlandini** [comment]
Hi @leo67867 
You said that you start the training from scratch. Does that mean not starting from https://github.com/BUTSpeechFIT/DiaPer/tree/main/models/10attractors/SC_LibriSpeech_2spk_adapted1-10 but rather without using any initial model? I expect that will perform much worse. The results I shared are fine-tuning the model already adapted to 1-10 speakers. I apologize if that was not clear

**Comment by leo67867** [comment]
Hello @fnlandini,

I have used the configuration file [this link](https://github.com/BUTSpeechFIT/DiaPer/blob/main/models/10attractors/SC_LibriSpeech_2spk_adapted1-10_finetuneAISHELL4mix/train.yaml), and modified the parameters inside to set init_epochs: 0 and init_model_path: '' (with the initial model path left empty). Then I ran the command python diaper/train.py -c DiaPer/models/10attractors/SC_LibriSpeech_2spk_adapted1-10_finetuneAISHELL4mix/train.yaml to train from scratch, hoping to achieve your results. However, the outcome is not ideal.

Could you please clarify why, when using the configuration file with the parameters you fine-tuned, I am unable to train from scratch and achieve similar results to yours? Should I proceed differently? For example, should I first train from scratch using the file [this link](https://github.com/BUTSpeechFIT/DiaPer/blob/main/models/10attractors/SC_LibriSpeech_2spk_adapted1-10/train.yaml), and after obtaining checkpoint files like checkpoint_91.tar to checkpoint_100.tar, modify the parameters init_epochs: 91-100 and init_model_path: 'https://github.com/BUTSpeechFIT/DiaPer/tree/main/models/10attractors/SC_LibriSpeech_2spk_adapted1-10/models', then continue training using the configuration file [this link](https://github.com/BUTSpeechFIT/DiaPer/blob/main/models/10attractors/SC_LibriSpeech_2spk_adapted1-10_finetuneAISHELL4mix/train.yaml)? Would this approach lead to your results?

Alternatively, what would be the correct approach to obtain your results? How should I train from scratch to replicate your results? If any of my explanations are unclear or if you need further information, please feel free to ask. You can also contact me directly via email. I look forward to your reply and greatly appreciate your assistance.

**Comment by fnlandini** [comment]
Hi @leo67867 
The problem is that you are expecting to obtain results that I never produced training from scratch. If you check the [paper](https://arxiv.org/pdf/2312.04324), all results for AISHELL-4 are after fine-tuning. The procedure is the following:
1. The model is trained on simulated conversation with 2 speakers per recording.
2. Taking the epochs 91-100 from the step above, adapt the average of those checkpoints on simulated conversations with 1-10 speakers per recording.
3. Taking the epochs 91-100 from the step above, fine-tune the average of those checkpoints on in-domain data, for example AISHELL-4.

So, you can do the fine-tuning step directly starting from https://github.com/BUTSpeechFIT/DiaPer/tree/main/models/10attractors/SC_LibriSpeech_2spk_adapted1-10/models as you mention as the second alternative in your message. This is the output of step 2 above.
Training from scratch on these small sets will lead to worse results. The model needs a larger training set at the beginning.

**Comment by leo67867** [comment]
Hello @fnlandini,
 I have been training on a small dataset like AISHELL-4 based on the pretraining results of simulated dialogues with 1-10 speakers per recording. However, the progress has not been satisfactory. Could you please share the larger dataset that the model initially requires?

Simulated dialogues with 2 speakers per recording (SC_LibriSpeech_2spk):
Train data directory: <data_dir>/data/SC_LibriSpeech/v1_2spks_2480.6h/--no-use-rirs--use-noises--no-use-energies/train/data
Validation data directory: <data_dir>/data/SC_LibriSpeech/v1_2spks_2480.6h/--no-use-rirs--use-noises--no-use-energies/validation/data

Simulated dialogues with 1-10 speakers per recording (SC_LibriSpeech_2spk_adapted1-10):
Train data directory: <data_dir>/data/SC_LibriSpeech/v1_1-10spks_all2500h/train/data
Validation data directory: <data_dir>/SC_LibriSpeech/v1_1-10spks_all2500h/validation/data

I would greatly appreciate it if you could provide these two larger datasets to facilitate my training. You can also send them via email; my email is ll7240252@gmail.com.

Thank you once again.

**Comment by fnlandini** [comment]
Hi @leo67867 
Unfortunately, it is not possible for me to share those datasets because they are a few tera bytes large.
However, you can generate the data yourself following https://github.com/BUTSpeechFIT/EEND_dataprep/tree/main/v2
I hope this helps

**Comment by leo67867** [comment]
Hello @fnlandini,
Could you please share the Kaldi-style data for SC_LibriSpeech_2spk and SC_LibriSpeech_2spk_adapted1-10 with me? Similar to the Kaldi-style data of AISHELL4_data.tar.gz, which is relatively small. Thank you very much for your help!
[AISHELL4_data.tar.gz](https://github.com/user-attachments/files/18434760/AISHELL4_data.tar.gz)

**Comment by fnlandini** [comment]
[SC_LibriSpeech_2spk_af.tar.gz](https://github.com/user-attachments/files/18469635/SC_LibriSpeech_2spk_af.tar.gz)
[SC_LibriSpeech_2spk_ae.tar.gz](https://github.com/user-attachments/files/18469637/SC_LibriSpeech_2spk_ae.tar.gz)
[SC_LibriSpeech_2spk_ad.tar.gz](https://github.com/user-attachments/files/18469636/SC_LibriSpeech_2spk_ad.tar.gz)
[SC_LibriSpeech_2spk_ac.tar.gz](https://github.com/user-attachments/files/18469633/SC_LibriSpeech_2spk_ac.tar.gz)
[SC_LibriSpeech_2spk_ab.tar.gz](https://github.com/user-attachments/files/18469634/SC_LibriSpeech_2spk_ab.tar.gz)
[SC_LibriSpeech_2spk_aa.tar.gz](https://github.com/user-attachments/files/18469638/SC_LibriSpeech_2spk_aa.tar.gz)

Hi, you need to `cat` them in order from `aa` to `af`. I do not have the 1-10 anymore but uploading it would not be possible (10x larger).

I hope this helps
